name = "hepex_green_agent"
description = "The assessment hosting agent for HEP-ex AnalysisOps benchmark."
version = "0.1.0"

defaultInputModes = ["text"]
defaultOutputModes = ["text"]

[capabilities]
streaming = false

[[skills]]
id = "host_assess_hepex_bench"
name = "HEP-ex assessment hosting"
description = """
Host and run the HEP-ex benchmark against a target (white) agent.
"""
tags = ["green agent", "assessment hosting", "hepex", "analysisops"]
examples = ["""
Your task is to instantiate HEP-ex benchmark to test the agent located at:
<white_agent_url>
http://localhost:9002/
</white_agent_url>
You should use the following env configuration:
<env_config>
{
  "task_spec_path": "src/bench/tasks/zll/task1_run/task.yaml",
  "runtime_limit_sec": 900,
  "max_num_steps": 20,
  "data_cache_dir": ".cache/atlas_opendata"
}
</env_config>
"""]
